Add dependency check to rootid
Now in that situation, the user will know why it's not working.
Admittedly, this is unlikely, but I like to handle errors.

diff --git a/rootid b/rootid
--- a/rootid
+++ b/rootid
@@ -1,6 +1,11 @@
 #!/bin/sh
 # Outputs the id of the root window
 
+if ! command -V xwininfo > /dev/null 2>&1; then
+	printf "ERROR: Dependency 'xwininfo' not met.\n" 1>&2
+	exit 1
+fi
+
 Count=0
 xwininfo -root | while read Line; do
 	case $Line in
